basic:
  name: InsightEye
  version: 1.0
  task: "ImageTag"
  n_gpus: 1
  seed: 666
  id2name: "configs/label2name/image_tag.json"

arch:
  type: efficentnet_b5
  resume:
  best_model: "/data/changqing/InsightEye_Pytorch/train_log/ImageTag_efficentnet_b5/0705_154245/ckpt/model_best_weight.pth"
  args:
    num_classes: 28

loader:
  data_aug:
    image_resize: 380
  type: normdataloader
  args:
    img_fmt: rgb
    dataset_name: path_label
    infer_data:
      data_file: "/data1/changqing/ZyImage_Data/annotations/test_annotations_20210713/images_paths_20210713.txt"
      is_train: false
      data_aug:
        image_resize: 380
    batch_size: 64
    pin_memory: true
    num_workers: 2
scheme:
  use_loader: false
  tensorboardx: false
  results_dir_name: "test_20210713"



