basic:
  name: InsightEye
  version: 1.0
  task_name: "ImageTag_cls47"
  task_type: "multi_class"
  n_gpus: 7
  seed: 666
  id2name: "configs/label2name/imgtag_cls47_idx2name.json"

arch:
  arch_type: efficentnet_b5
  resume: ""
  best_model: ""
  args:
    num_classes: 47
  use_ema: true
  ema_decay: 0.999

loader:
  type: normdataloader
  args:
    img_fmt: rgb
    dataset_name: path_label
    train_data:
      data_file: "/data1/changqing/ZyImage_Data/annotations/imgtag_cls47_train_shuffled.txt"
      loader_mode: train
      data_aug:
        image_resize: 380
        random_crop: true
        random_rotate: false
        random_hflip: true
        random_vflip: false
        gaussianblur: false
        random_erase: false
        random_gamma: false
        random_brightness: false
        random_saturation: false
        random_adjust_hue: false
    valid_data:
      data_file: "/data1/changqing/ZyImage_Data/annotations/imgtag_cls47_valid_shuffled.txt"
      loader_mode: valid
      data_aug:
        image_resize: 380
    batch_size: 64
    pin_memory: true
    num_workers: 4

solver:
  epochs: 30
  use_ema: False
  ema_decay: 0.999
  optimizer:
    type: SGD
    args:
      lr: 0.01
      momentum: 0.9
  lr_scheduler:
    type: StepLR
    args:
      step_size: 12
      gamma: 0.1
  save_dir: "workshop"
  ckpt_dir: "ckpt"
  log_dir: "log"
  save_max: 5
  save_freq:
  valid_interval:
  log_interval: 1
  verbosity: 1
  monitor: "valid_acc"
  monitor_mode: "max"
  tensorboardx: true
  resume: ""
  fix_random_seed:

loss: cross_entry_loss
metrics: common



