basic:
  name: InsightEye
  version: 1.0
  task: "InducedClick"

arch:
  type: efficentnet_b5
  args:
    num_classes: 4

env:
  n_gpus: 1
  img_resize: 380
  label2name: "configs/label2name/inducedclick.json"
  resume: ""




