basic:
  name: InsightEye
  version: 1.0
  task: "InducedClick"
  n_gpus: 1
  seed: 666
  id2name: "onfigs/label2name/inducedclick.json"

arch:
  type: efficentnet_b5
  resume: ""
  best_model: ""
  args:
    num_classes: 4

loader:
  type:
    args:
scheme:
  result_dir: ""
  tensorboardx: true



